# Generated by Django 5.2.2 on 2025-06-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('especificaciones', models.TextField(blank=True)),
                ('detalles_adicionales', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
