# Generated by Django 5.2.2 on 2025-06-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_componente_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaDestacada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='main.componente')),
            ],
        ),
    ]
