# Generated by Django 5.2.2 on 2025-06-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_caracteristicadestacada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='detalles_adicionales',
        ),
        migrations.AddField(
            model_name='componente',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='enlace_modelo_3d',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace al modelo 3D generado por SketchUp o Trimble', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='componente',
            name='especificaciones',
            field=models.TextField(help_text='Puedes usar formato JSON o texto plano.'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
