# Generated by Django 5.2.2 on 2025-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_componente_detalles_adicionales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='enlace_modelo_3d',
        ),
        migrations.AddField(
            model_name='componente',
            name='modelo_3d_embed',
            field=models.TextField(blank=True, help_text='Pega aquí el iframe completo del modelo 3D (por ejemplo, de Sketchfab)', null=True),
        ),
    ]
