# Generated by Django 5.2.2 on 2025-06-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_componente_enlace_modelo_3d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='modelo_3d_embed',
        ),
        migrations.AddField(
            model_name='componente',
            name='modelo_3d_url',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace al modelo 3D de Sketchfab (por ejemplo, https://sketchfab.com/models/ID)', null=True),
        ),
    ]
