# Generated by Django 5.2.2 on 2025-06-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_componente_modelo_3d_embed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='modelo_3d_url',
        ),
        migrations.AddField(
            model_name='componente',
            name='modelo_3d_file',
            field=models.FileField(blank=True, help_text='Sube aquí el archivo del modelo 3D (.glb, .gltf, etc.)', null=True, upload_to='modelos_3d/'),
        ),
    ]
