# Generated by Django 5.2.2 on 2025-06-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_componente_modelo_3d_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='modelo_3d_file',
        ),
        migrations.AddField(
            model_name='componente',
            name='modelo_3d_url',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace al modelo 3D de Sketchfab (por ejemplo, https://sketchfab.com/models/ID)', null=True),
        ),
    ]
