# Generated by Django 5.2.2 on 2025-06-12 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_componente_modelo_3d_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristicadestacada',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='caracteristicadestacada',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='caracteristicadestacada',
            name='valor',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componente',
            name='enlace_modelo_3d',
            field=models.URLField(blank=True, help_text='URL del modelo 3D de Sketchfab (ej: https://sketchfab.com/models/ID-MODELO)', max_length=500, null=True),
        ),
    ]
